---
title: "Tail Measurements"
author: "Anneke Kakebeen"
date: "8/14/2019 (Revised 09/27/19)"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Set up 
```{r set up, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}

# load packages 
library(ggplot2)
library(tidyr)
library(DT)
library(LaCroixColoR)
library(dplyr)
library(ggpubr)
library(cowplot)
library(Seurat)

# colors 
meisColor <- "#FBB58F"
pbxColor <- "#B574A7"
color <- lacroix_palette("CranRaspberry")

# source functions
source("~/Desktop/R_working/common_source_functions.R")


# set wd
setwd("~/Desktop/pax6 paper/Final Markdowns/TailMeasurement/")

```

## Load in data
```{r load data, echo=FALSE, warning=FALSE, cache=TRUE}

# read in data
MOdata <- read.csv("pbx3_meis1MO_regenmeasures_090919.csv")
MOdata$SampleFull <- paste(MOdata$Sample, MOdata$Timepoint, MOdata$Replicate, MOdata$Clutch, sep = ".") # make column with sampleID
MOdata$Clutch <- as.character(MOdata$Clutch) # set numerical values of clutch as a character 

# phenotype definition
# morphology: 1=WT, 2= full epidermal covering, 3=neither, 4=axial nub, 5=axial no fin
# neurons: 10=neurons in regen, 20=no neurons in regen, 30=not stained
# notocord: 100=stacked, 200=not stacked

# rename sc to spinal cord
MOdata$MeasureType <- (gsub(MOdata$MeasureType, pattern = "sc", replacement = "Spinal Cord"))
MOdata$MeasureType <- factor(MOdata$MeasureType, levels = c("Tail", "Spinal Cord", "Spinal Cord_width")) # factor measurement type for plot 

# view data
datatable(MOdata)

```

## Figure 6AA: Plot tail measurement data
### All Timepoints
```{r plot1 data, echo=FALSE, warning=FALSE, cache=TRUE}

# boxplot to compare measurement data across cntrl, meis1MO, and pbx3 MO 
TailS <- filter(MOdata, MeasureType %in% c("Tail", "Spinal Cord")) # filter table for only tail and spinal cord measurements
comparisons <- list(c("cntrl", "meis1MO1"),c("cntrl", "meis1MO2"),c("cntrl", "pbx3MO1"),c("cntrl", "pbx3MO2")) # define comparisons for statistics


# plot all timepoints
ggplot(TailS, aes(x=SampleID, y=Measurement, fill=SampleID)) + # define dataframe and paramters
  geom_boxplot() + # make boxplot
  geom_jitter() + # add points on top of boxplots
  theme_bw(base_size = 20) + # adjust text size
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + # adjust graph look (remove gridlines)
  facet_grid(Timepoint~MeasureType) + # divide graph by timepoint and measurement type
  ylim(0, 1000) + # define axis limit
  ylab(expression(paste("Length ", mu, "m"))) + # label y axis
  xlab("") + # remove xaxis title
   stat_compare_means(comparisons = comparisons, method = "t.test", label.y = c(750, 825, 900, 970), label = "p.signif") + # add statistical test
    Seurat:::RotatedAxis() + # rotate xaxis names
  scale_fill_manual(values = c("white",meisColor, meisColor, pbxColor, pbxColor)) # call fill colors


```

### Plot only 72hpa for figure
```{r 6AA, echo=FALSE, warning=FALSE, cache=TRUE}

# plot 72hpa
ggplot(filter(TailS, Timepoint == "72hpa"), aes(x=SampleID, y=Measurement, fill=SampleID)) +
  geom_boxplot() +
  geom_jitter() +
  theme_bw(base_size = 20) +
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(colour = "black"), axis.text.y = element_text(colour = "black")) +
  facet_grid(Timepoint~MeasureType) +
  ylim(0, 1000) +
  ylab(expression(paste("Length ", mu, "m"))) +
  xlab("") +
   stat_compare_means(comparisons = comparisons, method = "t.test", label.y = c(750, 825, 900, 975), label = "p.signif") +
    Seurat:::RotatedAxis() +
  scale_fill_manual(values = c("white",meisColor, meisColor, pbxColor, pbxColor))


```


## Plot phenotypic analysis of coded phenotypes
### Descriptors
```{r phenotype1, echo=FALSE, warning=FALSE, cache=TRUE}

# convert numberical values to phenotypic descriptors MORPHOLOGY
MOdata$PhenotypeMorphology <- gsub(MOdata$PhenotypeMorphology, pattern = "1", replacement = "Wild-type") 
MOdata$PhenotypeMorphology <- gsub(MOdata$PhenotypeMorphology, pattern = "2", replacement = "FinCoverage")
MOdata$PhenotypeMorphology <- gsub(MOdata$PhenotypeMorphology, pattern = "3", replacement = "Other")
MOdata$PhenotypeMorphology <- gsub(MOdata$PhenotypeMorphology, pattern = "4", replacement = "AxialNub")
MOdata$PhenotypeMorphology <- gsub(MOdata$PhenotypeMorphology, pattern = "5", replacement = "AxialSpike(SansFin)")
MOdata$PhenotypeMorphology <- factor(MOdata$PhenotypeMorphology, levels = c("Wild-type", "AxialNub", "FinCoverage", "AxialSpike(SansFin)", "Other"))
  
# convert numberical values to phenotypic descriptors NOTOCORD
MOdata$PhenotypeNotocord <- gsub(MOdata$PhenotypeNotocord, pattern = "1", replacement = "Stacked") 
MOdata$PhenotypeNotocord <- gsub(MOdata$PhenotypeNotocord, pattern = "2", replacement = "NotStacked")
MOdata$PhenotypeNotocord <- factor(MOdata$PhenotypeNotocord, levels = c("Stacked", "NotStacked"))


# convert numberical values to phenotypic descriptors NEURONS
MOdata$PhenotypeNeuron <- gsub(MOdata$PhenotypeNeuron, pattern = "1", replacement = "Regen") 
MOdata$PhenotypeNeuron <- gsub(MOdata$PhenotypeNeuron, pattern = "2", replacement = "NotInRegen")
MOdata$PhenotypeNeuron <- gsub(MOdata$PhenotypeNeuron, pattern = "0", replacement = "NoStain")
MOdata$PhenotypeNeuron <- factor(MOdata$PhenotypeNeuron, levels = c("Regen", "NotInRegen", "NoStain"))

```

### Plot Phenotype Morphology: Histogram
```{r phenotype2, echo=FALSE, warning=FALSE, cache=TRUE}

# Histogram for Morphology
ggplot(data = filter(MOdata,MeasureType == "Tail"), aes(x=PhenotypeMorphology, fill=PhenotypeMorphology)) +
  geom_histogram(stat = "count") +
    scale_fill_manual(values = color) + # changes color of box 
  theme(legend.position = "none") + # change legend position
  facet_grid(Sample~Timepoint) + # make facets by measurement type and timepoint
  theme_bw() +
  ggtitle("Morphology") +
  Seurat:::RotatedAxis()


# Stacked barplot of phenotypes
Phenoplot <- filter(MOdata, MeasureType == "Tail" & Timepoint == "72hpa")
#Phenoplot <- table( Phenoplot$PhenotypeMorphology, Phenoplot$Sample)
Phenoplot$PhenotypeMorphology <- factor(Phenoplot$PhenotypeMorphology, levels = c("Wild-type", "AxialNub", "FinCoverage", "AxialSpike(SansFin)", "Other"))

```


### Plot Phenotype Morphology:Stacked bar
```{r phenotype3, echo=FALSE, warning=FALSE, cache=TRUE}
# Waffle charts of phenotypes
filterdata <- filter(MOdata,MeasureType == "Tail")
testfreq <- as.data.frame(table(filterdata$Sample, filterdata$Timepoint, filterdata$PhenotypeMorphology))
testtotal <- as.data.frame(table(filterdata$Sample, filterdata$Timepoint))
test <- merge.data.frame(testfreq, testtotal, by = c("Var1", "Var2"))
colnames(test) <- c("sample", "timepoint", "phenotype", "freq", "total")
test$percent <- (test$freq/test$total)*100

# stacked barplot
ggplot(test, aes(x=sample, y=percent, fill=phenotype)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = color[c(1,3,4,5,6)]) +
  facet_grid(timepoint~.)
```

### Plot Phenotype Morphology: Waffle chart
```{r phenotype4, echo=FALSE, warning=FALSE, cache=TRUE}
source("wafflechart.R")

# waffle chart
p1 <- waffle_chart(filter(test, timepoint == "24hpa"), 
             fill = "phenotype", value = "percent",facet = "sample", fill_colors = color[c(1,3,4,5,6)]) 
p2 <- waffle_chart(filter(test, timepoint == "48hpa"), 
             fill = "phenotype", value = "percent",facet = "sample", fill_colors = color[c(1,3,4,5,6)]) 
p3 <- waffle_chart(filter(test, timepoint == "72hpa"), 
             fill = "phenotype", value = "percent",facet = "sample", fill_colors = color[c(1,3,4,5,6)]) 


plot_grid(p1, p2, p3, labels = c("24hpa", "48hpa", "72hpa"),  nrow = 3)



```

