---
title: "Test"
author: "Anneke Kakebeen"
date: "2/26/2020"
always_allow_html: yes
output:
  github_document:
    toc: true
    toc_depth: 3
---

## load settings
```{r load libraries, echo=FALSE, warning=FALSE, message=FALSE}

# load packages 
library(ggplot2)
library(tidyr)
library(DT)
library(LaCroixColoR)
library(dplyr)
library(ggpubr)
library(cowplot)
library(Seurat)
library(patchwork)

# colors 
uninjColor <- "white"
tracerColor <- "#D9565C"
meisColor <- "#FBB58F"
pbxColor <- "#B574A7"
color <- lacroix_palette("CranRaspberry")

# source functions
source("~/Desktop/R_working/common_source_functions.R")


# set wd
setwd("~/Desktop/pax6 paper/Final Markdowns/TailMeasurement/")


```


## load data
```{r load data, echo=FALSE, warning=FALSE, cache=TRUE}

# read in data
MOdata <- read.csv("pbx3_meis1MO_regenmeasures_021220.csv")
MOdata$SampleFull <- paste(MOdata$Sample, MOdata$Timepoint, MOdata$Replicate, MOdata$Clutch, sep = ".") # make column with sampleID
MOdata$Clutch <- as.character(MOdata$Clutch) # set numerical values of clutch as a character 

# phenotype definition
# morphology: 1=WT, 2= full epidermal covering, 3=neither, 4=axial nub, 5=axial no fin
# neurons: 10=neurons in regen, 20=no neurons in regen, 30=not stained
# notocord: 100=stacked, 200=not stacked

# rename sc to spinal cord
MOdata$MeasureType <- (gsub(MOdata$MeasureType, pattern = "sc", replacement = "Spinal Cord"))
MOdata$MeasureType <- factor(MOdata$MeasureType, levels = c("Tail", "Spinal Cord", "Spinal Cord_width")) # factor measurement type for plot 

```
## Figure 6AA: Plot tail measurement data
### Vivo-MO measurements
```{r plot data, echo=FALSE, warning=FALSE, cache=TRUE}
# filter data for last clutch with correct doses
vmo_022120 <- filter(MOdata, Clutch == "22120")
#factor data to order sample variables correctly
vmo_022120$SampleID <- factor(vmo_022120$SampleID, levels = c("uninjected", "tracer", "meis1_VMO", "pbx3_VMO"))
# define comparisons for statistics
comparisons <- list(c("uninjected", "tracer"),c("uninjected", "meis1_VMO"),c("uninjected", "pbx3_VMO"),c("tracer", "meis1_VMO"), c("tracer", "pbx3_VMO")) # define comparisons for statistics

ggplot(vmo_022120, aes(x=SampleID, y=Measurement, fill=SampleID)) +
  geom_boxplot() +
  geom_jitter() +
  theme_bw(base_size = 20) +
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(colour = "black"), axis.text.y = element_text(colour = "black")) +
  ylab(expression(paste("Length ", mu, "m"))) +
  xlab("") +
  facet_grid("MeasureType") +
   stat_compare_means(comparisons = comparisons, method = "t.test", label = "p.signif") +
    Seurat:::RotatedAxis() +
  scale_fill_manual(values = c(uninjColor,tracerColor, pbxColor, meisColor))


```


## Figure Supp 6AA: Plot tail measurement data
### All Timepoints
```{r plot1 data, echo=FALSE, warning=FALSE, cache=TRUE}

# boxplot to compare measurement data across cntrl, meis1MO, and pbx3 MO 
TailS <- filter(MOdata, SampleID %in% c("cntrl", "meis1MO1", "pbx3MO1", "meis1MO2", "pbx3MO2"))
TailS <- filter(TailS, MeasureType %in% c("Tail", "Spinal Cord")) # filter table for only tail and spinal cord measurements
comparisons <- list(c("cntrl", "meis1MO1"),c("cntrl", "meis1MO2"),c("cntrl", "pbx3MO1"),c("cntrl", "pbx3MO2")) # define comparisons for statistics


# plot all timepoints
ggplot(TailS, aes(x=SampleID, y=Measurement, fill=SampleID)) + # define dataframe and paramters
  geom_boxplot() + # make boxplot
  geom_jitter() + # add points on top of boxplots
  theme_bw(base_size = 20) + # adjust text size
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + # adjust graph look (remove gridlines)
  facet_grid(Timepoint~MeasureType) + # divide graph by timepoint and measurement type
  ylim(0, 1000) + # define axis limit
  ylab(expression(paste("Length ", mu, "m"))) + # label y axis
  xlab("") + # remove xaxis title
   stat_compare_means(comparisons = comparisons, method = "t.test", label.y = c(750, 825, 900, 970), label = "p.signif") + # add statistical test
    Seurat:::RotatedAxis() + # rotate xaxis names
  scale_fill_manual(values = c("white",meisColor, meisColor, pbxColor, pbxColor)) # call fill colors


```

### Plot only 72hpa for figure
```{r 6AA, echo=FALSE, warning=FALSE, cache=TRUE}

# boxplot to compare measurement data across cntrl, meis1MO, and pbx3 MO 
TailS <- filter(MOdata, SampleID %in% c("cntrl", "meis1MO1", "pbx3MO1", "meis1MO2", "pbx3MO2"))
TailS <- filter(TailS, MeasureType %in% c("Tail", "Spinal Cord")) # filter table for only tail and spinal cord measurements
TailS <- filter(TailS, Timepoint == "72hpa")
comparisons <- list(c("cntrl", "meis1MO1"),c("cntrl", "meis1MO2"),c("cntrl", "pbx3MO1"),c("cntrl", "pbx3MO2")) # define comparisons for statistics

# plot 72hpa
ggplot(TailS, aes(x=SampleID, y=Measurement, fill=SampleID)) +
  geom_boxplot() +
  geom_jitter() +
  theme_bw(base_size = 20) +
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.text.x = element_text(colour = "black"), axis.text.y = element_text(colour = "black")) +
  facet_grid(Timepoint~MeasureType) +
  ylim(0, 1000) +
  ylab(expression(paste("Length ", mu, "m"))) +
  xlab("") +
   stat_compare_means(comparisons = comparisons, method = "t.test", label.y = c(750, 825, 900, 975), label = "p.signif") +
    Seurat:::RotatedAxis() +
  scale_fill_manual(values = c("white",meisColor, meisColor, pbxColor, pbxColor))


```


